import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import * as productsController from "../controllers/products.js";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const Router = express.Router();
Router.get("/", productsController.getProducts);
// Router.post("/products", productsController.getAddProducts);
export default Router;
