import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import * as productsController from "../controllers/shop.js";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const Router = express.Router();
Router.get("/", productsController.getIndex);
Router.get("/products", productsController.getProducts);
// Router.post("/products", productsController.getProducts);
// Router.get("/products/:productId", productsController.getProduct);
// Router.get("/cart", productsController.getCart);
// Router.post("/cart-delete-item", productsController.postCardDeleteCart);
// Router.post("/cart", productsController.postCard);
// Router.get("/orders", productsController.getOrder);
// Router.get("/checkout", productsController.checkout);
// Router.post("/create-order", productsController.postOrder);
export default Router;
